src/main/java/com/woowacourse/pelotonbackend/config/JdbcConfig.java, src/main/java/com/woowacourse/pelotonbackend/member/domain/Member.java, src/main/java/com/woowacourse/pelotonbackend/mission/domain/Mission.java, src/main/java/com/woowacourse/pelotonbackend/missioncertification/domain/MissionCertification.java, src/main/java/com/woowacourse/pelotonbackend/missioncertificationreport/domain/MissionCertificationReport.java, src/main/java/com/woowacourse/pelotonbackend/race/domain/Race.java, src/main/java/com/woowacourse/pelotonbackend/rider/domain/Rider.java, src/main/java/com/woowacourse/pelotonbackend/support/AggregateReferenceValueExtractor.java, src/main/resources/META-INF/services/javax.validation.valueextraction.ValueExtractor
=> 엔티티 저장 전 Validator 동작 구현

src/main/java/com/woowacourse/pelotonbackend/member/domain/Member.java, src/main/java/com/woowacourse/pelotonbackend/mission/domain/Mission.java, src/main/java/com/woowacourse/pelotonbackend/missioncertification/domain/MissionCertification.java, src/main/java/com/woowacourse/pelotonbackend/race/domain/Race.java
=> feat: Embedded된 필드들에 대하여 Validator가 동작하도록 구현

src/main/resources/schema.sql
=> refactor: schema.sql에서 외래키 제거

peloton-frontend/.expo/packager-info.json, peloton-frontend/App.js, peloton-frontend/component/Root.js, peloton-frontend/component/certification/Certification.js, peloton-frontend/component/home/Home.js, peloton-frontend/component/home/HomeMain.js, peloton-frontend/component/home/RaceDetail.js, peloton-frontend/component/profile/Profile.js
=> 프론트엔드 화면 뼈대 구성

src/main/java/com/woowacourse/pelotonbackend/certification/domain/Certification.java, src/main/java/com/woowacourse/pelotonbackend/certification/domain/CertificationRepository.java, src/main/java/com/woowacourse/pelotonbackend/certification/domain/CertificationStatus.java, src/main/java/com/woowacourse/pelotonbackend/mission/domain/MissionInstruction.java, src/main/java/com/woowacourse/pelotonbackend/mission/domain/TimeDuration.java, src/main/java/com/woowacourse/pelotonbackend/missioncertification/domain/MissionCertificationRepository.java, src/main/java/com/woowacourse/pelotonbackend/missioncertification/domain/MissionCertificationStatus.java, src/main/java/com/woowacourse/pelotonbackend/missioncertificationreport/domain/MissionCertificationReportRepository.java, src/main/java/com/woowacourse/pelotonbackend/race/domain/DateDuration.java, src/main/java/com/woowacourse/pelotonbackend/report/domain/Report.java, src/main/java/com/woowacourse/pelotonbackend/report/domain/ReportRepository.java, src/main/java/com/woowacourse/pelotonbackend/report/domain/ReportType.java, src/main/java/com/woowacourse/pelotonbackend/vo/Cash.java, src/main/java/com/woowacourse/pelotonbackend/vo/ImageUrl.java, src/main/resources/schema.sql, src/test/java/com/woowacourse/pelotonbackend/certification/domain/CertificationRepositoryTest.java, src/test/java/com/woowacourse/pelotonbackend/member/domain/MemberRepositoryTest.java, src/test/java/com/woowacourse/pelotonbackend/mission/domain/MissionRepositoryTest.java, src/test/java/com/woowacourse/pelotonbackend/race/domain/RaceRepositoryTest.java, src/test/java/com/woowacourse/pelotonbackend/report/domain/ReportRepositoryTest.java, src/test/java/com/woowacourse/pelotonbackend/rider/domain/RiderRepositoryTest.java
- Repository test 작성
- Entity, package naming 수정
- VO에 Value annotation 적용
close #56 , close #47
=> feat: 도메인 스키마 일치 테스트 및 네이밍 수정

.gitmodules
=> refactor: Submodule 인증을 기존 https 방식에서 ssh 인증 방식으로 변경

.github/workflows/gradle.yml
=> feat: Github actions CI

.github/ISSUE_TEMPLATE/------.md
=> chore: 이슈 템플릿 적용

src/main/java/com/woowacourse/pelotonbackend/common/ErrorCode.java, src/main/java/com/woowacourse/pelotonbackend/common/exception/RiderNotFoundException.java, src/main/java/com/woowacourse/pelotonbackend/race/presentation/dto/RaceRetrieveResponse.java, src/main/java/com/woowacourse/pelotonbackend/rider/application/RiderService.java, src/main/java/com/woowacourse/pelotonbackend/rider/domain/RiderCustomRepository.java, src/main/java/com/woowacourse/pelotonbackend/rider/domain/RiderRepository.java, src/main/java/com/woowacourse/pelotonbackend/rider/domain/RiderRepositoryImpl.java, src/main/java/com/woowacourse/pelotonbackend/rider/presentation/RiderController.java, src/main/java/com/woowacourse/pelotonbackend/rider/presentation/RiderResponse.java, src/main/java/com/woowacourse/pelotonbackend/rider/presentation/dto/RiderCreateRequest.java, src/test/java/com/woowacourse/pelotonbackend/rider/acceptance/RiderAcceptanceTest.java, src/test/java/com/woowacourse/pelotonbackend/rider/application/RiderServiceTest.java, src/test/java/com/woowacourse/pelotonbackend/rider/domain/RiderFixture.java, src/test/java/com/woowacourse/pelotonbackend/rider/domain/RiderRepositoryTest.java, src/test/java/com/woowacourse/pelotonbackend/rider/presentation/RiderControllerTest.java
=> 라이더 생성 및 조회 기능 완료했습니다.

peloton-frontend/component/home/HomeNavigationRoot.js, peloton-frontend/component/home/homemain/HomeBanner.js, peloton-frontend/component/home/race/RaceDetail.js, peloton-frontend/component/home/racecreate/CalendarButton.js, peloton-frontend/component/home/racecreate/CategorySelection.js, peloton-frontend/component/home/racecreate/InputBox.js, peloton-frontend/component/home/racecreate/InputRaceDates.js, peloton-frontend/component/home/racecreate/InputRaceFee.js, peloton-frontend/component/home/racecreate/RaceCreateUnit.js, peloton-frontend/utils/constants.js
=> 레이스 생성 화면 UI 수정

src/main/java/com/woowacourse/pelotonbackend/member/presentation/dto/MemberCashUpdateRequest.java
서버에 캐시 충전 요청 시 발생하는 MismatchedInputException 해결
=> Hotfix: 서버에 캐시 충전 요청 시 발생하는 문제 해결

.gitmodules
=> refactor: git submodule의 url을 http 방식으로 변경

.github/workflows/gradle.yml
- 러너 os를 ubuntu-latest 로 수정
- 오타 수정
=> fix: GitHub actions ci

.github/workflows/gradle.yml
=> chore: gradle.yml 토큰 오타 수정

src/main/java/com/woowacourse/pelotonbackend/common/GlobalExceptionHandler.java, src/main/java/com/woowacourse/pelotonbackend/member/domain/Member.java, src/test/java/com/woowacourse/pelotonbackend/member/presentation/MemberControllerTest.java
=> refactor: 프로필 사진이 null일 경우 db 저장 허용 및 ConstraintViolationException 예외처리 로직 구현

src/main/resources/application.yml, src/main/resources/db/changes/changelog-schema-1.0.1.xml
=> fix: Spring boot Profile을 읽어올 수 없던 버그 수정

src/main/java/com/woowacourse/pelotonbackend/member/application/MemberService.java, src/main/java/com/woowacourse/pelotonbackend/member/presentation/LoginMemberArgumentResolver.java, src/test/java/com/woowacourse/pelotonbackend/infra/login/LoginMemberArgumentResolverTest.java, src/test/java/com/woowacourse/pelotonbackend/member/presentation/LoginMemberArgumentResolverIntegrationTest.java
#193 을 실수로 브랜치를 따서, 다시 보냅니다 😄 
리뷰 반영했어요~
=> refactor: ArgumentResolver 예외 처리 및 테스트 구현

peloton-frontend/utils/constants.js
=> fix: submodule update

src/docs/asciidoc/api-guide.adoc, src/main/java/com/woowacourse/pelotonbackend/config/WebMvcConfig.java, src/main/java/com/woowacourse/pelotonbackend/query/application/QueryService.java, src/main/java/com/woowacourse/pelotonbackend/query/presentation/QueryController.java, src/main/java/com/woowacourse/pelotonbackend/race/application/RaceService.java, src/main/java/com/woowacourse/pelotonbackend/race/domain/RaceRepository.java, src/main/java/com/woowacourse/pelotonbackend/race/presentation/RaceController.java, src/main/java/com/woowacourse/pelotonbackend/race/presentation/dto/RaceResponse.java, src/main/java/com/woowacourse/pelotonbackend/race/presentation/dto/RaceResponses.java, src/main/java/com/woowacourse/pelotonbackend/rider/presentation/dto/RiderResponses.java, src/test/java/com/woowacourse/pelotonbackend/docs/QueryDocumentation.java, src/test/java/com/woowacourse/pelotonbackend/infra/login/LoginMemberArgumentResolverTest.java, src/test/java/com/woowacourse/pelotonbackend/member/application/MemberServiceTest.java, src/test/java/com/woowacourse/pelotonbackend/member/domain/MemberFixture.java, src/test/java/com/woowacourse/pelotonbackend/member/presentation/MemberControllerTest.java, src/test/java/com/woowacourse/pelotonbackend/member/presentation/dto/MemberResponsesTest.java, src/test/java/com/woowacourse/pelotonbackend/query/application/QueryServiceTest.java, src/test/java/com/woowacourse/pelotonbackend/query/presentation/QueryControllerTest.java, src/test/java/com/woowacourse/pelotonbackend/race/RaceAcceptanceTest.java, src/test/java/com/woowacourse/pelotonbackend/race/application/RaceServiceTest.java, src/test/java/com/woowacourse/pelotonbackend/race/domain/RaceFixture.java, src/test/java/com/woowacourse/pelotonbackend/race/presentation/RaceControllerTest.java, src/test/java/com/woowacourse/pelotonbackend/rider/domain/RiderFixture.java
=> feat: Member id로 참여중인 race들을 모두 조회하는 기능

src/main/java/com/woowacourse/pelotonbackend/race/presentation/dto/RaceResponses.java, src/test/java/com/woowacourse/pelotonbackend/docs/QueryDocumentation.java
=> fix: race responses에 jsonNamingStrategy 추가

src/main/java/com/woowacourse/pelotonbackend/certification/application/CertificationService.java, src/main/java/com/woowacourse/pelotonbackend/infra/upload/S3UploadService.java, src/main/java/com/woowacourse/pelotonbackend/member/application/MemberService.java, src/main/java/com/woowacourse/pelotonbackend/support/RandomGenerator.java, src/main/java/com/woowacourse/pelotonbackend/support/RandomGeneratorImpl.java, src/test/java/com/woowacourse/pelotonbackend/infra/upload/UploadFixture.java, src/test/java/com/woowacourse/pelotonbackend/member/domain/MemberFixture.java, src/test/java/com/woowacourse/pelotonbackend/member/presentation/dto/MemberProfileResponseTest.java
=> fix: S3 경로 문제 해결

src/main/resources/static/index.html
=> feat: API 문서를 index 페이지에 추가

peloton-frontend/component/profile/profileedit/UnregisterButtonContainer.js
- 탈퇴 후 redirect 페이지를 메인화면에서 로그인 화면으로 변경
- 탈퇴 버튼 클릭 시 뜨는 메시지, 로그 메시지 수정
=> fix: 회원 탈퇴 버튼을 클릭 후 발생하는 버그 해결

src/main/java/com/woowacourse/pelotonbackend/certification/domain/CertificationSql.java, src/main/java/com/woowacourse/pelotonbackend/query/presentation/QueryController.java, src/test/java/com/woowacourse/pelotonbackend/certification/domain/CertificationRepositoryTest.java, src/test/java/com/woowacourse/pelotonbackend/query/presentation/QueryControllerTest.java
- Certification 쿼리 서비스에서 Image를 불러오지 않는 버그 수정
- QueryController mapping url 수정
=> fix: certification query 관련 수정

peloton-frontend/component/home/homemain/RaceItem.js, peloton-frontend/component/home/homemain/RaceItemImage.js, peloton-frontend/component/home/homemain/RaceItemText.js, peloton-frontend/component/home/homemain/RaceItems.js, peloton-frontend/component/home/homemain/RaceList.js, peloton-frontend/component/home/race/RaceDetail.js, peloton-frontend/state/race/ResponseState.js, peloton-frontend/utils/constants.js, src/main/java/com/woowacourse/pelotonbackend/race/domain/RaceCategory.java
- 없으면 프론트에서 임시 이미지를 사용하도록 함
- 백에서 레이스 create를 할 때 ramdom url이 제대로 들어가도록 image url 추가
close #214
=> feat: Member가 본인이 참여중인 레이스를 home화면에 볼 수 있는 기능

src/main/java/com/woowacourse/pelotonbackend/certification/presentation/dto/CertificationResponse.java, src/test/java/com/woowacourse/pelotonbackend/certification/domain/CertificationFixture.java, src/test/java/com/woowacourse/pelotonbackend/certification/presentation/CertificationControllerTest.java, src/test/java/com/woowacourse/pelotonbackend/certification/presentation/dto/CertificationResponseTest.java, src/test/java/com/woowacourse/pelotonbackend/docs/CertificationDocumentation.java
=> fix: Certification Response에 CreatedAt 필드 추가

src/test/java/com/woowacourse/pelotonbackend/certification/domain/CertificationFixture.java
=> fix: certification fixture formatting

src/main/java/com/woowacourse/pelotonbackend/certification/domain/CertificationRepositoryCustom.java, src/main/java/com/woowacourse/pelotonbackend/certification/domain/CertificationRepositoryCustomImpl.java, src/main/java/com/woowacourse/pelotonbackend/certification/domain/CertificationSql.java, src/main/java/com/woowacourse/pelotonbackend/query/application/QueryService.java, src/test/java/com/woowacourse/pelotonbackend/certification/domain/CertificationFixture.java, src/test/java/com/woowacourse/pelotonbackend/certification/domain/CertificationRepositoryTest.java, src/test/java/com/woowacourse/pelotonbackend/query/application/QueryServiceTest.java
미션 id들로 인증목록을 불러올 때, Rider id도 포함되어있는지 검사하는 방식으로 수정했습니다.
=> fix: 인증 목록을 불러올 때, 남의 인증목록을 가져오던 버그 수정

peloton-frontend/component/home/homemain/RaceList.js, peloton-frontend/component/home/race/RaceDeepLinkPage.js, peloton-frontend/component/home/racecreate/InputRaceFee.js, peloton-frontend/component/login/ChangeProfile.js, peloton-frontend/component/login/Login.js, peloton-frontend/component/profile/ProfileImageEditButton.js, peloton-frontend/component/profile/profileedit/CashUpdate.js, peloton-frontend/component/profile/profileedit/NameUpdate.js, peloton-frontend/utils/api/MemberApi.js, peloton-frontend/utils/api/RaceApi.js, peloton-frontend/utils/api/RiderApi.js, src/main/java/com/woowacourse/pelotonbackend/common/ErrorCode.java, src/test/java/com/woowacourse/pelotonbackend/member/presentation/LoginMemberArgumentResolverIntegrationTest.java
메시지가 맘에 안드실 수 있어요!
좋은 메세지 있으면 `아니`  라는 대답과 이유 혹은 대안을 제시해주면 좋을 것 같습니다😊
resolves #154
=> ErrorCode 클래스에서 Code를 변경했습니다.

peloton-frontend/component/profile/profiledetail/AchievementItem.js, peloton-frontend/component/profile/profiledetail/AchievementItems.js, peloton-frontend/component/profile/profiledetail/ProfileDetail.js, peloton-frontend/component/profile/profileedit/UnregisterButtonContainer.js, peloton-frontend/state/certification/AchievementRatesState.js, peloton-frontend/utils/api/MemberApi.js, peloton-frontend/utils/api/QueryApi.js, peloton-frontend/utils/constants.js
=> feat: 성취율 프론트 페이지 구현

src/main/java/com/woowacourse/pelotonbackend/member/domain/Member.java, src/main/java/com/woowacourse/pelotonbackend/query/presentation/dto/RaceAchievementRates.java, src/test/java/com/woowacourse/pelotonbackend/member/domain/MemberFixture.java, src/test/java/com/woowacourse/pelotonbackend/query/presentation/dto/RaceAchievementRatesTest.java
애매해서 고려해보고 머지할지 abort할지 결정해야 할 것 같아요..
다른방법은 아예 탈퇴한 회원의 결과에 대해선 보여주지 않는 방법도 한가지 방법이긴해요.
=> fix: 회원이 탈퇴한 경우 생기는 버그 수정

src/main/java/com/woowacourse/pelotonbackend/config/WebMvcConfig.java, src/main/resources/public/secure.html
=> feat: 개인정보처리방침 추가

peloton-frontend/component/ApplicationNavigationRoot.js, peloton-frontend/component/home/HomeNavigationRoot.js, peloton-frontend/component/home/race/CalculationResult.js, peloton-frontend/component/home/race/CalculationResults.js, peloton-frontend/component/home/race/HalfWidthButton.js, peloton-frontend/component/home/race/LinkCopyButton.js, peloton-frontend/component/home/race/RaceCalculation.js, peloton-frontend/component/home/race/RaceDetail.js, peloton-frontend/state/certification/RaceAchievementState.js, peloton-frontend/utils/api/CalculationApi.js, peloton-frontend/utils/api/QueryApi.js
=> feat: 정산 프론트 페이지 구현

peloton-frontend/component/login/KakaoLoginWebView.js, peloton-frontend/component/setting/AnnouncementItem.js, peloton-frontend/utils/constants.js
=> feat: 메일 앱 연결 구현

peloton-frontend/component/setting/AnnouncementItem.js
=> feat: 화살표 추가했습니다

.gitignore, peloton-frontend/component/home/race/RaceDetail.js, peloton-frontend/component/home/race/RaceSpec.js, peloton-frontend/component/home/racecreate/RaceCreateUnit.js, peloton-frontend/package-lock.json, peloton-frontend/package.json, peloton-frontend/webpack.config.js, peloton-frontend/yarn.lock
시각화 결과는 peloton-frontend에서 터미널에 `expo build:web`로 확인할 수 있습니다.
resolve: #320 이슈 [댓글](https://github.com/woowacourse-teams/2020-14f-guys/issues/320) 보시면 과정과 결과 정리해놓았습니다.
=> chore: 정적 파일 시각화 기능 추가 및 경량화
